name: PR Review Reminder

on:
  schedule:
    - cron: "0 16 * * 1-5" # M-F @ 11am CST
  workflow_dispatch:

jobs:
  remind-reviewer:
    runs-on: ubuntu-latest
    steps:
      - run: echo Sending reminder to requested reviewers.
      - uses: davideviolante/pr-reviews-reminder-action@v1.6.1
        env:
            GITHUB_TOKEN: ${{ secrets.MARVIN_TOKEN }}
        with:
            webhook-url: ${{ secrets.SLACK_WEBHOOK_RECIPES_CHANNEL }}
            provider: 'slack'
            channel: ${{ secrets.RECIPES_CHANNEL }}
      - run: echo Reminder sent!
